### ISSUE TITLE
Support All Access tracks

### ISSUE THREAD

**Issue by aqtrans** [DanNixon/PlayMusicCL#21]
I cannot seem to get this working on ArchLinux running with Python 2.7.8, it spits out the following:
```
9146@11:42:23-aqtrans@homer|~/build/PlayMusicCL$ playmusiccl
** Message: pygobject_register_sinkfunc is deprecated (GstObject)
Logging in to Google Play Music...
Logging in to Last.fm...
Creating GStreamer player...
Updating local library from Google Play Music...
Traceback (most recent call last):
  File "/usr/bin/playmusiccl", line 9, in <module>
    load_entry_point('playmusiccl==0.6.0', 'console_scripts', 'playmusiccl')()
  File "/usr/lib/python2.7/site-packages/playmusiccl-0.6.0-py2.7.egg/playmusiccl/__init__.py", line 7, in run
    main()
  File "/usr/lib/python2.7/site-packages/playmusiccl-0.6.0-py2.7.egg/playmusiccl/playmusiccl.py", line 746, in main
    __MusicClient__.update_local_lib()
  File "/usr/lib/python2.7/site-packages/playmusiccl-0.6.0-py2.7.egg/playmusiccl/playmusiccl.py", line 111, in update_local_lib
    song = song_map[track["trackId"]]
KeyError: u'Thh4ppuotycvjyhlw2tkpxz7inm'
```
I installed both PlayMusicCL and Unofficial-Google-Music-API from git.
I did have to make some slight modifications to the PlayMusicCL scripts in order to allow them to run properly in the python3/python2 ArchLinux environment:
```
9136@11:38:50-aqtrans@homer|~$ head -n1 /usr/lib/python2.7/site-packages/playmusiccl/playmusiccl.py
#!/usr/bin/python2
9137@11:38:56-aqtrans@homer|~$ head -n1 /usr/bin/playmusiccl 
#!/usr/bin/python2
```
The "Updating local library from Google Play Music..." bit seems to take a while, and stracing the process does show some successful communication, so I think it's logging in at least.

**Comment by nwalters512** [comment]
Is this issue ever going to be fixed? I just installed playmusiccl and got this error. I am using a Play Music All Access account on a Raspberry Pi running the latest version of Raspbian.

**Comment by DanNixon** [comment]
As per the conversation so far, supporting all access with the current API would break existing features (unless of course Tue API has since changed).

I have neither an all access account or the time to look at this right now.

**Comment by lpar** [comment]
How about making the README warn of the problem? Something like:

> A command line client for Google Play Music. Note that it does not support Google Play All Access.

**Comment by DanNixon** [comment]
I give in, I'll try to fix all access if someone is available to test it for me.

**Comment by lpar** [comment]
I volunteer. I'm running Debian and installed PlayMusicCL using pip. I'm a sysadmin and developer, but not a Python developer.

**Comment by DanNixon** [comment]
Cool. I admit I may not get round to this for a few weeks as I'm fairly busy with full time and evening work at the moment.

**Comment by lpar** [comment]
This should make things easier:
http://www.androidcentral.com/google-play-music-launches-free-ad-supported-version-us

**Comment by DanNixon** [comment]
I'm in the UK.

**Comment by Naosyth** [comment]
For anyone who just wants a quick fix and doesn't mind losing playlist support (and possibly introducing other bugs): Comment out lines 101 - 111 in playmusiccl.py

After doing this, it should be able to stream all access music fine. This is what I'm doing until a proper fix is available.

**Comment by DanNixon** [comment]
PR #26 seems to have fixed this, my playlists with a combination of all access and uploaded tracks now work.
If those originally having the problem are happy I will close this.
